### ISSUE TITLE
Left nav - Missing book depending on which page is loaded

### ISSUE THREAD

**Issue by iansk** [hlxsites/prisma-cloud-docs-website#101]
The number of books in the left nav changes depending on which page of which book is open. (To keep things clear, I've used the following format for links: `PRODUCT > BOOK`)

If you go to this page in the `compute` product, there are only four books:

[Compute > Operationalize Guide](https://main--prisma-cloud-docs-website--hlxsites.hlx.live/prisma/prisma-cloud/en/compute/ops-guide)

However, if you go to this page in the `compute` product, there are five books:

[Compute > Admin Guide - version pcee](https://main--prisma-cloud-docs-website--hlxsites.hlx.live/prisma/prisma-cloud/en/compute/pcee/admin-guide)

**Comment by maxakuru** [comment]
I don't think this is a bug

`ops-guide` is an unversioned book, so it only shows itself and the other 3 unversioned books
`compute` IS versioned, so it shows itself and the 4 versioned books

**Comment by iansk** [comment]
@maxakuru For a given product, the number of books in the left ToC should be static, even a specific book is versioned (e.g. the Admin Guide is versioned, but it should always be visible in the ToC)

If you go to this [page](https://main--prisma-cloud-docs-website--hlxsites.hlx.live/prisma/prisma-cloud/en/compute/ops-guide) in the Compute doc set, there are four books in the ToC:

<img width="345" alt="compute-ops" src="https://github.com/hlxsites/prisma-cloud-docs-website/assets/6518946/260901a4-b3fd-4576-a8ad-9ebf2c57112e">

But if you go to this [page](https://main--prisma-cloud-docs-website--hlxsites.hlx.live/prisma/prisma-cloud/en/compute/pcee/admin-guide) in the Comptue doc set, there are five books in the ToC:

<img width="345" alt="compute-admin" src="https://github.com/hlxsites/prisma-cloud-docs-website/assets/6518946/f4c3f9ae-8948-4dff-a975-ae12eb3976fd">

**Comment by icaraps** [comment]
@iansk  Similar to https://github.com/hlxsites/prisma-cloud-docs-website/issues/64#issuecomment-1605536907, it looks like the the formula for all-books in column J of the metadata sheet outputs 4 books for `compute/ops-guide` and 5 books for `compute/pcee`.

**Comment by maxakuru** [comment]
@iansk the problem here is still in the metadata, I think there's some confusion so I'll try to be complete here..

Here's a screenshot of all the rows for the compute product in the `all-books` sheet:
<img width="1603" alt="Screenshot 2023-07-10 at 2 10 27 PM" src="https://github.com/hlxsites/prisma-cloud-docs-website/assets/17409558/95d94fc0-aa5a-4609-b839-199c95c7c9b0">

**blue numbers**: entries that appear for versioned books whose version matches between the `sheet1` and `all-books` sheets
**red numbers**: appear for all books in the product

If a version cell is empty in the `all-books` sheet, that row will appear for all books in the product, since the filter in `sheet1` checks for a matching version OR an empty string. You may notice that the unversioned pages in the `sheet1` metadata use `not-applicable`; that's on purpose so that you can do things with them, like assign specific books to the sidenavs of these unversioned books.

To summarize the book version cases:
- use empty string for a book that should always appear in the product's sidenav, regardless of version or versioned/unversioned type
- use a specific version for a book that only applies to that specific version of the product
- use `not-applicable` for a book that applies to only unversioned book pages in the product

In the example above, the `all-books` sheet is missing an entry for `Administrator’s Guide` with version `not-applicable`. I'll leave that change up to you since I'm not sure what the path should be for unversioned pages (pcee/latest version/etc.)

There's one other issue with the compute product in `all-books`, and that's a missing pcee book as mentioned in https://github.com/hlxsites/prisma-cloud-docs-website/issues/64#issuecomment-1629733023

**Comment by maxakuru** [comment]
nothing to fix, closing
