### ISSUE TITLE
Handling non-existent topics

### ISSUE THREAD

**Issue by iansk** [hlxsites/prisma-cloud-docs-website#103]
When entering a URL for an adoc file that doesn't exist in the repo, the result is unexpected.

**Repro:**

1. Go the following link. The URL specifies a file `docs/en/compute/ops-guide/getting-started/timeline2`that doesn't exist in the prisma-cloud-docs repo.

   https://main--prisma-cloud-docs-website--hlxsites.hlx.live/prisma/prisma-cloud/en/compute/ops-guide/getting-started/timeline2

2. Notice the URL in the address bar.

   https://main--prisma-cloud-docs-website--hlxsites.hlx.live/prisma/prisma-cloud/en/compute/not-applicable/ops-guide/getting-started/getting-started

**Results:**

You get redirected to a page that loads, but doesn't give you much information about what happened.

Notice the `not-applicable` part in the URL path.

**Expected Results:**

@maxakuru Was this design intentional? If so, what do you think about adding a brief message, i.e. "File doesn't exist", or something similar?

What do you think is the best option/experience here?

**Comment by maxakuru** [comment]
@iansk this was from #18, which was implemented after we talked about this scenario on slack.. I believe it was your suggestion to redirect to the first topic in the book when a document doesn't exist, which would be particularly useful for version/language switcher since docs won't be 1:1 across each

the redirect logic itself seems like it's got a bug, the `not-applicable` path segment shouldn't be added

**Comment by iansk** [comment]
@maxakuru That's right, I remember that discussion on Slack. Let's keep the logic the same, but fix the `not-applicable` bug.

**Comment by maxakuru** [comment]
this is fixed now
