### ISSUE TITLE
Embedded Gdoc doesn't load

### ISSUE THREAD

**Issue by iansk** [hlxsites/prisma-cloud-docs-website#120]
I tried embedding another GDoc into an adoc file. For this particular GDoc, neither the left nav nor the adoc content load.

**Additional details:**

* Branch and commit with my changes: https://github.com/hlxsites/prisma-cloud-docs/compare/main...ian-complex-gdoc2

* Gdoc that we're embedding: https://docs.google.com/document/d/1ZZexutVSK0tjHF0WYgt5tuHAf61pQOID1bq66nnC4-o/edit

* Screenshot of what's rendered in the preview:

   <img width="1468" alt="embed-gdoc-not-loading" src="https://github.com/hlxsites/prisma-cloud-docs-website/assets/6518946/09c9e539-eeee-4f0e-b645-e545a9a98dbb">

* Link to the preview: https://main--prisma-cloud-docs-website--hlxsites.hlx.page/prisma/prisma-cloud/en/compute/30-xx/admin-guide/welcome/field-guide?branch=ian-complex-gdoc2

**Comment by icaraps** [comment]
@maxakuru The issue seems to come from tables in the gdoc that are misinterpreted as blocks for example: 

<img width="650" alt="Screenshot 2023-07-07 at 10 30 05" src="https://github.com/hlxsites/prisma-cloud-docs-website/assets/6012307/92373d37-581c-4f9f-85ff-8180d494bb0d">
<img width="673" alt="Screenshot 2023-07-07 at 10 30 26" src="https://github.com/hlxsites/prisma-cloud-docs-website/assets/6012307/2a6e7f99-20f7-488f-81ec-b96fb302ac49">

And because the blocks (eg policy-description) don't exist in the github repo, the whole article remains in unloaded status which is hidden by default. 

I also noticed that some icons are misinterpreted. For example here, Franklin tries to load an icon named "nameid-format". 

<img width="656" alt="Screenshot 2023-07-07 at 10 31 01" src="https://github.com/hlxsites/prisma-cloud-docs-website/assets/6012307/670c489d-f8bf-4273-8366-dfc26b92ecc4">

**Comment by maxakuru** [comment]
@icaraps was correct, and as we talked about today the ideal solution for the tables being converted to non-existent blocks is to wrap those tables in a `table` block

the 2nd issue with icons is another issue, I don't believe it's contributing to this problem where the page is blank due to the section status not being updated, but worth fixing anyway - I'll make another issue for it
