### ISSUE TITLE
Left nav - book order

### ISSUE THREAD

**Issue by iansk** [hlxsites/prisma-cloud-docs-website#50]
We'd like the order of the books in the left nav to be fixed, and we'd like to be able to explicitly specify the order. (Maybe it makes sense to specify order in the metadata sheet?)

Currently, the selected book moves to the top of the nav. For example.

1. Navigate to the [Compute Admin Guide](https://main--prisma-cloud-docs-website--hlxsites.hlx.live/prisma/prisma-cloud/en/compute/pcee/admin-guide).

   The Admin Guide appears at the top of the left nav.

   <img width="343" alt="left-nav-order1" src="https://github.com/hlxsites/prisma-cloud-docs-website/assets/6518946/b03a7332-4ae2-46a2-ad0f-b00cd186350f">

2. Click on the Reference Architecture book. The Ref Arch book moves to the top of the left nav, and the previously selected Admin Guide moves into second position.

   <img width="342" alt="left-nav-order2" src="https://github.com/hlxsites/prisma-cloud-docs-website/assets/6518946/51b32680-1a49-4d97-aac4-390373c7e401">

**Expected results:**

If the specified order of the books is:

1. Admin Guide
2. Intelligence Stream Notifications
4. Operationalize Guide
5. Public Sector
6. Reference Architecture

Then the Admin Guide should always be at the top, and the Ref Arch should always be at the bottom.

**Comment by maxakuru** [comment]
@iansk the order will be fixed in #54 and will follow the order in metadata

it's worth mentioning that the titles of the books need to match between the metadata and content inside the `book.yml`

reason for this is that the "main book" data is loaded immediately, from the book.json (which is from book.yml), and the entry in the sidenav comes from that data, then other books in the sidenav use the title from metadata and only are loaded when hovered. If the titles don't match, then the title will change on hover and/or the title will differ for pages inside the book vs. pages that include the book as an "additional book"
