### ISSUE TITLE
Can't load book content for some products

### ISSUE THREAD

**Issue by iansk** [hlxsites/prisma-cloud-docs-website#57]
Books for the cns, code-security, and cspm products don't load.

These are the links I tried to access. They all return `404 Page Not Found` errors.

* https://main--prisma-cloud-docs-website--hlxsites.hlx.live/prisma/prisma-cloud/en/cns/saas/admin-guide
* https://main--prisma-cloud-docs-website--hlxsites.hlx.live/prisma/prisma-cloud/en/code-security/admin-guide
* https://main--prisma-cloud-docs-website--hlxsites.hlx.live/prisma/prisma-cloud/en/cspm/admin-guide

Books for the compute product load fine:

* https://main--prisma-cloud-docs-website--hlxsites.hlx.live/prisma/prisma-cloud/en/compute/30-xx/admin-guide

**Comment by maxakuru** [comment]
@iansk I've added the other products to the fstab folder mapping in #75

in theory we could do a single folder mapping for each locale rather than by product, but that means we lose the pretty 404 on a lot of pages.. if this method becomes unmanageable it can be changed at that point

just be aware that the fstab needs to be updated for each additional language/product
