### ISSUE TITLE
Left nav - performance

### ISSUE THREAD

**Issue by iansk** [hlxsites/prisma-cloud-docs-website#66]
When loading the site from scratch, it takes a long time before you can interact with the left nav bar. From my tests (my system, my internet connection), it takes about 6 seconds, which detracts from snappy performance from the rest of the site.

The experience is: the site loads fast, I'm ready to drill into the nav (to explore or to go somewhere specific), there's a noticeable delay, wait, wait, wait....okay, now I can use the nav bar.

Measurement (there's probably a better way):

1. Open an incognito Chrome tab.

2. Start QuickTime player.

3. Start screen recording.

4. Enter [link](
https://main--prisma-cloud-docs-website--hlxsites.hlx.live/prisma/prisma-cloud/en/compute/ops-guide/getting-started/timeline) into browser tab, hit return.

5. After site fully loads, stop the screen recording.

6. Save the screen recording.

7. Open the screen recording in QuickTime.

8. Enter Cmd-T to enter the trim view in QuickTime. This shows time in milliseconds.

9. Move the scrubber to the point where the browser tab first shows the loading animation. Take note of the time.

10. Move the scrubber to the point where the left is fully loaded (when you see the `>` markers). Take note of the time.

11. Subtract end time from start time.

See .mov file here: https://github.com/hlxsites/prisma-cloud-docs-website/assets/6518946/554ef636-62a9-4d0f-863f-f562a1d0edc8

**Comment by maxakuru** [comment]
I believe this isn't actually a usability issue like you described, since the sidenav should be functional before those icons show up.

the problem is that we ported the icons from the previous site, which are bundled as large font files ([font-awesome (70kb)](https://github.com/hlxsites/prisma-cloud-docs-website/blob/main/prisma/prisma-cloud/icons/fontawesome/fontawesome-webfont.woff2), [ionicons (84kb)](https://github.com/hlxsites/prisma-cloud-docs-website/blob/main/prisma/prisma-cloud/icons/ionicons/ionicons.woff2), [simple-line-icons (29kb)](https://github.com/hlxsites/prisma-cloud-docs-website/blob/main/prisma/prisma-cloud/icons/simple-line-icons/Simple-Line-Icons.woff2)) & a companion [stylesheet (105kb)](https://github.com/hlxsites/prisma-cloud-docs-website/blob/main/prisma/prisma-cloud/styles/icons.css). 

The combined `~290kb` was greatly impacting the site's performance when loaded normally so to avoid that impact we're currently loading the icons in the "delayed" phase, which is 3 seconds after the page loads. Obviously this ends up with broken/missing icons for a noticeable duration, but without smaller icons we really can't load them earlier or the entire site will get hit.. 

for this particular case, we can just find chevrons and use those for the sidenav (see #81). But the real solution is to replace the font icons with an svg sprite sheet, or at least individual svg files, and replace all usage of font icons in code/content. Since I don't have access/license to get SVGs for the icons you were using previously, I'll leave this as a todo for your guys later.

**Comment by iansk** [comment]
@maxakuru I played with the preview in https://github.com/hlxsites/prisma-cloud-docs-website/pull/81, and it looks good to me.

**Comment by icaraps** [comment]
> But the real solution is to replace the font icons with an svg sprite sheet, or at least individual svg files, and replace all usage of font icons in code/content.

Just for reference, I opened an issue a while ago for this https://github.com/hlxsites/prisma-cloud-docs-website/issues/33
