### ISSUE TITLE
Can't load doc page

### ISSUE THREAD

**Issue by iansk** [hlxsites/prisma-cloud-docs-website#83]
For some reason, I cannot load this page in my browser:

https://main--prisma-cloud-docs-website--hlxsites.hlx.live/prisma/prisma-cloud/en/compute/not-applicable/ops-guide/getting-started/test-sitemap

The file, `test-sitemap.adoc` was created and merged into `main` with this PR: https://github.com/hlxsites/prisma-cloud-docs/commit/581df718c90a579546574fc59c37f718869c4f47

The Franklin admin API seems to report an abnormal status for the file:

https://admin.hlx.page/status/hlxsites/prisma-cloud-docs/main/prisma/prisma-cloud/docs/en/compute/ops-guide/getting-started/test-sitemap

This is what I see in my Chrome browser when I try to load the file:

<img width="1471" alt="cannot-load-doc-page" src="https://github.com/hlxsites/prisma-cloud-docs-website/assets/6518946/c9220386-c608-45a3-986a-11d2d6c6d0ab">

**Comment by maxakuru** [comment]
this is because the filename has an underscore, which should be caught on PR.. added path normalization before publish in https://github.com/hlxsites/prisma-cloud-docs/pull/32, but this particular case won't be fixed by that.

we can add a check to disallow these bad filenames: https://github.com/hlxsites/prisma-cloud-docs/issues/33

for future reference, you can check the job for a merge to `main` to see the status of publishes, for example: https://github.com/hlxsites/prisma-cloud-docs/actions/runs/5318685196/jobs/9630411868

<img width="1459" alt="Screenshot 2023-06-21 at 12 14 05 PM" src="https://github.com/hlxsites/prisma-cloud-docs-website/assets/17409558/614c41b5-f13e-499d-997c-80e301ac596f">
