### ISSUE TITLE
Left nav - content shifts/shakes/jumps when titles are long

### ISSUE THREAD

**Issue by iansk** [hlxsites/prisma-cloud-docs-website#89]
Some book titles don't full load in the ToC when you initially go to a page. Then, when you hover over the book titles, they fully load. If the book title is long, the ToC jumps to vertically expand to accommodate the longer string, pushing all subsequent entries further down. It's a bit of a jarring experience, since there's been no user interaction yet (e.g. a click).

**Repro steps:**

1. Load this [page](https://main--prisma-cloud-docs-website--hlxsites.hlx.live/prisma/prisma-cloud/en/compute/ops-guide/phases/learn):

   <img width="343" alt="left-nav-jump1" src="https://github.com/hlxsites/prisma-cloud-docs-website/assets/6518946/039d12c5-8ec3-44a0-aac2-661bd5dc4521">

2.  Hover over to ToC, specifically the "Prisma Cloud Reference Architecture" entry.

   <img width="345" alt="left-nav-jump2" src="https://github.com/hlxsites/prisma-cloud-docs-website/assets/6518946/b3882da3-23cf-4674-86e3-55ef414fa6ac">

**Results:**

The "Prisma Cloud Reference Architecture" entry fully loads and becomes  "Prisma Cloud Reference Architecture (Compute)". The old string required one line, but the new longer string requires two lines, so the subsequent entry in the ToC jumps down to accommodate the extra space required.

**Expected results:**

All book titles in the ToC fully load on page load. Hovering over entries doesn't cause anything to jump/expand unless and entry is clicked on.

**Comment by maxakuru** [comment]
@iansk this is because the titles used inside the `book.yml` are different from those used in the metadata sheet

we use 2 sources for the sidenav top level entries:
1. book -> for the "main book" (ie. the book the current page belongs to) ([example](https://github.com/hlxsites/prisma-cloud-docs/blob/main/docs/en/compute/ref-arch/book.yml#L3))
2. metadata -> for all other books in sidenav ([example](https://docs.google.com/spreadsheets/d/1wcEpQHnidF960FtX-SFHzYP4RE5Z4L4plXKiKl8WiIY/edit?pli=1#gid=313623260&range=10:10))

Reason to do this is that we avoid loading the json of all other books until we actually need it, which is when the user's mouse goes to click/expand the book in the menu. On mouseover, we load that book's data and replace the menu item with the fully hydrated list. If the title is different it gets swapped at this point. We could stop it from swapping the title, but there will then be a difference between pages for book titles - imo we should just fix the differences between those 2 sources

**Comment by icaraps** [comment]
>  imo we should just fix the differences between those 2 sources

+1

**Comment by iansk** [comment]
@maxakuru Thanks for the detailed explanation. I agree that it's best to fix the differences between the two sources, as you suggested. I'll do it now, and republish the metadata sheet.

**Comment by iansk** [comment]
@icaraps Thanks for the extra fix

**Comment by iansk** [comment]
@maxakuru Does it make sense to remove the code that later loads the title from `book.yml`, and just always load from the metadata sheet? Once you hand over the keys to us, I think it'll be confusing for any future maintainers that there are two possible sources for the title. I can't think of a use case where we'd want to overwrite the title from `book.yml`, especially it's a jarring user experience if the titles are vastly different strings.

Is there anything else you're pulling from `book.yml` that's already defined in the metadata sheet?

I think simplifying the code/logic is a nice win. Let me know what you think.

**Comment by maxakuru** [comment]
@iansk believe it or not that would actually be more complicated logic; right now on mouseover we just load the book data and recreate the sidenav element, then replace the old with the new "hydrated" list. If we want to keep the text the same, we'd need to also change the inner text of a child element to match the previous element. Not a big change but it isn't more simple..

I still think the solution is just to fix either the content or the metadata, and then staying consistent throughout. If they don't match there will always be places where things seems out of sync, since we'll still be using the metadata entry for the current book title

if you're adamant that you want the title in the sidenav to be [able to be] different for the book when it's selected/being viewed vs. when it's one of the "additional" books, we can make it do the logic above
